In [3]:
import numpy as np
import torch

In [2]:
torch.empty(3,3).normal_(mean = 0, std = 0.1)

tensor([[ 0.0895, -0.0288, -0.2906],
        [-0.1886,  0.0820,  0.0108],
        [ 0.0879, -0.0832,  0.0205]])

In [3]:
from torch import nn
import torch.nn.functional as F
from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5,), (0.5,)),
                              ])
# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

In [4]:
# Build a feed-forward network
model = nn.Sequential(nn.Linear(784, 128),
                      nn.ReLU(),
                      nn.Linear(128, 64),
                      nn.ReLU(),
                      nn.Linear(64, 10),
                      nn.LogSoftmax(dim = 1))

# Define the loss
criterion = nn.NLLLoss()

# Get our data
dataiter = iter(trainloader)

images, labels = next(dataiter)

# Flatten images
images = images.view(images.shape[0], -1)

# Forward pass, get our logits
logits = model(images)
# Calculate the loss with the logits and the labels
loss = criterion(logits, labels)

print(loss)

tensor(2.2871, grad_fn=<NllLossBackward0>)


In [5]:
print(logits.shape)
print(labels.shape)

torch.Size([64, 10])
torch.Size([64])


In [6]:
x = nn.NLLLoss()
x(logits, labels)

tensor(2.2871, grad_fn=<NllLossBackward0>)

In [7]:
labels

tensor([8, 8, 2, 9, 6, 4, 8, 1, 4, 4, 7, 4, 5, 8, 1, 8, 1, 2, 3, 7, 0, 6, 1, 7,
        0, 9, 1, 0, 9, 6, 6, 7, 2, 5, 8, 4, 0, 7, 7, 4, 7, 5, 1, 9, 1, 2, 4, 7,
        4, 1, 9, 9, 2, 6, 3, 2, 0, 4, 0, 8, 8, 1, 2, 2])

In [8]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()
# 2D loss example (used, for example, with image inputs)
# N, C = 5, 4
# loss = nn.NLLLoss()
# # input is of size N x C x height x width
# data = torch.randn(N, 16, 10, 10)
# conv = nn.Conv2d(16, C, (3, 3))
# m = nn.LogSoftmax(dim=1)
# # each element in target has to have 0 <= value < C
# target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
# output = loss(m(conv(data)), target)
# output.backward()

In [9]:
x = torch.arange(0., 5., requires_grad = True)
x

tensor([0., 1., 2., 3., 4.], requires_grad=True)

In [10]:
y = torch.dot(x, x)
print(y)
y.backward()

tensor(30., grad_fn=<DotBackward0>)


In [11]:
print(x.grad)

tensor([0., 2., 4., 6., 8.])


In [12]:
x = torch.tensor(10., requires_grad = True)
y = 2 * x ** 2 + 3
# y.backward()
# x.grad
z = 5 * y ** 2 + 5
z.backward()
print(x.grad)
y.is_leaf

tensor(81200.)


False

In [14]:
# for i in range(5):
#     y.backward(retain_graph=True)
#     print(x.grad)
    # x.grad.zero_()

In [15]:
x = torch.arange(1.,6., requires_grad = True)
print(x)
y = x.mean()
print(y)
y.backward()
print(x.grad)

tensor([1., 2., 3., 4., 5.], requires_grad=True)
tensor(3., grad_fn=<MeanBackward0>)
tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])


In [16]:
x = torch.arange(1., 6., requires_grad = True)
print(x)
y = x ** 2 + 2
print(y)
y.backward(torch.ones(5))
x.grad

tensor([1., 2., 3., 4., 5.], requires_grad=True)
tensor([ 3.,  6., 11., 18., 27.], grad_fn=<AddBackward0>)


tensor([ 2.,  4.,  6.,  8., 10.])

In [17]:
torch.tensor(1).item()

1

In [23]:
import torch
from torch import nn
import torch.nn.functional as F

In [7]:
class Network(nn.Module):
    def __init__(self, input_size, output_size, hidden_layers, drop_p=0.5):
        ''' Builds a feedforward network with arbitrary hidden layers.
        
            Arguments
            ---------
            input_size: integer, size of the input layer
            output_size: integer, size of the output layer
            hidden_layers: list of integers, the sizes of the hidden layers
        
        '''
        super().__init__()
        # Input to a hidden layer
        self.hidden_layers = nn.ModuleList([nn.Linear(input_size, hidden_layers[0])])
        
        # Add a variable number of more hidden layers
        layer_sizes = zip(hidden_layers[:-1], hidden_layers[1:])
        self.hidden_layers.extend([nn.Linear(h1, h2) for h1, h2 in layer_sizes])
        
        self.output = nn.Linear(hidden_layers[-1], output_size)
        
        self.dropout = nn.Dropout(p=drop_p)
        
    def forward(self, x):
        ''' Forward pass through the network, returns the output logits '''
        
        for each in self.hidden_layers:
            x = F.relu(each(x))
            x = self.dropout(x)
        x = self.output(x)
        
        return F.log_softmax(x, dim=1)

In [8]:
model = Network(784, 10, [512, 256, 128])

In [12]:
model.hidden_layers[0]

Linear(in_features=784, out_features=512, bias=True)

In [1]:
# function to create a model
# - Input layers, Output classes, hidden layers list, 

In [4]:
import torch.nn as nn
import torch.nn.functional as F

In [37]:
class Model_Creator(nn.Module):
    def __init__(self, input_layers, output_layers, hidden_layer_list, drop_p = 0.3):
        super().__init__()
        
        self.hidden_layer = nn.ModuleList([nn.Linear(input_layers, hidden_layer_list[0])])
        
        self.hidden_layer.extend([nn.Linear(hidden_layer_list[i], hidden_layer_list[i+1]) for i in range(len(hidden_layer_list)-1)])
        
        self.output_layer = nn.Linear(hidden_layer_list[-1], output_layers)
        
        self.dropout = nn.Dropout(drop_p)
        
    def forward(self, x):
        
        for layer in self.hidden_layer:
            x = F.relu(layer(x))
            x = self.dropout(x)
        
        x = self.output_layer(x)
        
        return f.log_softmax(x, dim = 1)

In [38]:
model1 = Model_Creator(784, 10, [512, 256, 128, 64, 32], 0.5)

In [39]:
model1

Model_Creator(
  (hidden_layer): ModuleList(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): Linear(in_features=512, out_features=256, bias=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): Linear(in_features=64, out_features=32, bias=True)
  )
  (output_layer): Linear(in_features=32, out_features=10, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)

In [1]:
if 0.018306 <= 0.017168:
    print('xdd')

In [15]:
import torch.nn as nn
# pool of square window of size=3, stride=2
m = nn.MaxPool2d(3, stride=2)
# pool of non-square window
m = nn.MaxPool2d(2, 4)
input = torch.randn(1, 8, 8)
output = m(input)

In [16]:
output.shape

torch.Size([1, 2, 2])