In [1]:
import numpy as np
import torch

In [2]:
torch.empty(3,3).normal_(mean = 0, std = 0.1)

tensor([[ 0.0486,  0.0672, -0.0330],
        [-0.1651,  0.1323, -0.1613],
        [-0.0693, -0.0291,  0.0342]])

In [ ]:
from torch import nn
import torch.nn.functional as F
from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5,), (0.5,)),
                              ])
# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

NameError: name 'torch' is not defined

In [ ]:
# Build a feed-forward network
model = nn.Sequential(nn.Linear(784, 128),
                      nn.ReLU(),
                      nn.Linear(128, 64),
                      nn.ReLU(),
                      nn.Linear(64, 10),
                      nn.LogSoftmax(dim = 1))

# Define the loss
criterion = nn.NLLLoss()

# Get our data
dataiter = iter(trainloader)

images, labels = next(dataiter)

# Flatten images
images = images.view(images.shape[0], -1)

# Forward pass, get our logits
logits = model(images)
# Calculate the loss with the logits and the labels
loss = criterion(logits, labels)

print(loss)

In [5]:
print(logits.shape)
print(labels.shape)

torch.Size([64, 10])
torch.Size([64])


In [6]:
x = nn.NLLLoss()
x(logits, labels)

tensor(2.3199, grad_fn=<NllLossBackward0>)

In [7]:
labels

tensor([6, 3, 8, 7, 9, 2, 7, 3, 8, 4, 6, 1, 4, 9, 9, 7, 5, 0, 1, 1, 9, 0, 3, 8,
        5, 8, 2, 3, 3, 8, 0, 9, 9, 1, 4, 6, 8, 0, 1, 6, 0, 8, 2, 9, 1, 8, 2, 8,
        9, 0, 2, 5, 7, 6, 1, 1, 8, 3, 5, 2, 9, 4, 4, 4])

In [8]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()
# 2D loss example (used, for example, with image inputs)
# N, C = 5, 4
# loss = nn.NLLLoss()
# # input is of size N x C x height x width
# data = torch.randn(N, 16, 10, 10)
# conv = nn.Conv2d(16, C, (3, 3))
# m = nn.LogSoftmax(dim=1)
# # each element in target has to have 0 <= value < C
# target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
# output = loss(m(conv(data)), target)
# output.backward()

In [32]:
x = torch.arange(0., 5., requires_grad = True)
x

tensor([0., 1., 2., 3., 4.], requires_grad=True)

In [33]:
y = torch.dot(x, x)
print(y)
y.backward()

tensor(30., grad_fn=<DotBackward0>)


In [34]:
print(x.grad)

tensor([0., 2., 4., 6., 8.])


In [117]:
x = torch.tensor(10., requires_grad = True)
y = 2 * x ** 2 + 3
# y.backward()
# x.grad
z = 5 * y ** 2 + 5
z.backward()
print(x.grad)
y.is_leaf

tensor(81200.)


False

In [111]:
for i in range(5):
    y.backward(retain_graph=True)
    print(x.grad)
    # x.grad.zero_()

tensor(-40.)
tensor(-80.)
tensor(-120.)
tensor(-160.)
tensor(-200.)


In [122]:
x = torch.arange(1.,6., requires_grad = True)
print(x)
y = x.mean()
print(y)
y.backward()
print(x.grad)

tensor([1., 2., 3., 4., 5.], requires_grad=True)
tensor(3., grad_fn=<MeanBackward0>)
tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])


In [133]:
x = torch.arange(1., 6., requires_grad = True)
print(x)
y = x ** 2 + 2
print(y)
y.backward(torch.ones(5))
x.grad

tensor([1., 2., 3., 4., 5.], requires_grad=True)
tensor([ 3.,  6., 11., 18., 27.], grad_fn=<AddBackward0>)


tensor([ 2.,  4.,  6.,  8., 10.])

In [137]:
torch.tensor(1).item()

1